### ISSUE TITLE
dirt.value.$atomics is not a function

### ISSUE THREAD

**Issue by cjroebuck** [vkarpov15/mongoose-unique-array#13]
When saving a document I'm getting

```
TypeError: dirt.value.$atomics is not a function
    at has$push (/dev/node_modules/mongoose-unique-array/index.js:123:16)
    at /dev/node_modules/mongoose-unique-array/index.js:101:11
    at Array.forEach (<anonymous>)
    at model.<anonymous> (/dev/node_modules/mongoose-unique-array/index.js:99:21)
    at callMiddlewareFunction (/dev/node_modules/kareem/index.js:483:23)
    at model.next (/dev/node_modules/kareem/index.js:58:7)
    at _next (/dev/node_modules/kareem/index.js:107:10)
    at /dev/node_modules/kareem/index.js:508:38
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

when I print the value of dirt, it is:

```
DIRT {
   path: 'updatedAt',
   value: 2021-09-18T01:12:42.598Z,
   schema: SchemaDate {
     path: 'updatedAt',
     instance: 'Date',
     validators: [],
     getters: [],
     setters: [],
     _presplitPath: [ 'updatedAt' ],
     options: SchemaDateOptions { type: [Function: Date] },
     _index: null,
     [Symbol(mongoose#schemaType)]: true
   }
 }
```

so as you can see `dirt.value` in this case is just a simple Date, hence attempting to call the `$atomics` function on it gives this error. 

Quick fix is to modify `has$push` function:

```diff
function has$push(dirt) {
  return dirt.value != null &&
+   dirt.value.$atomics &&   // check function exists here before calling it
    dirt.value.$atomics() != null &&
    '$push' in dirt.value.$atomics();
}
```

**Comment by vkarpov15** [comment]
I haven't been able to repro this, it shouldn't be possible for `has$push()` to be called on a non-array path. But we released v0.4.1 with the fix anyway :+1:
