### ISSUE TITLE
"SyntaxError: Unexpected end of JSON input" on install

### ISSUE THREAD

**Issue by Krister-Johansson** [vkarpov15/mongoose-unique-array#4]
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   'mongoose-unique-array',
1 verbose cli   '--save' ]
2 info using npm@5.6.0
3 info using node@v9.3.0
4 verbose npm-session 5c4f3b76153902f3
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/mongoose-unique-array 167ms (from cache)
8 silly pacote tag manifest for mongoose-unique-array@latest fetched in 182ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly saveTree imd@1.0.0
12 silly saveTree ├─┬ async@2.6.0
12 silly saveTree │ └── lodash@4.17.4
12 silly saveTree ├─┬ basic-auth@2.0.0
12 silly saveTree │ └── safe-buffer@5.1.1
12 silly saveTree ├─┬ body-parser@1.18.2
12 silly saveTree │ ├── bytes@3.0.0
12 silly saveTree │ ├── content-type@1.0.4
12 silly saveTree │ ├─┬ debug@2.6.9
12 silly saveTree │ │ └── ms@2.0.0
12 silly saveTree │ ├── depd@1.1.1
12 silly saveTree │ ├─┬ http-errors@1.6.2
12 silly saveTree │ │ ├── inherits@2.0.3
12 silly saveTree │ │ ├── setprototypeof@1.0.3
12 silly saveTree │ │ └── statuses@1.3.1
12 silly saveTree │ ├── iconv-lite@0.4.19
12 silly saveTree │ ├─┬ on-finished@2.3.0
12 silly saveTree │ │ └── ee-first@1.1.1
12 silly saveTree │ ├── qs@6.5.1
12 silly saveTree │ ├─┬ raw-body@2.3.2
12 silly saveTree │ │ └── unpipe@1.0.0
12 silly saveTree │ └─┬ type-is@1.6.15
12 silly saveTree │   ├── media-typer@0.3.0
12 silly saveTree │   └─┬ mime-types@2.1.17
12 silly saveTree │     └── mime-db@1.30.0
12 silly saveTree ├─┬ express@4.16.2
12 silly saveTree │ ├─┬ accepts@1.3.4
12 silly saveTree │ │ └── negotiator@0.6.1
12 silly saveTree │ ├── array-flatten@1.1.1
12 silly saveTree │ ├── content-disposition@0.5.2
12 silly saveTree │ ├── cookie-signature@1.0.6
12 silly saveTree │ ├── cookie@0.3.1
12 silly saveTree │ ├── encodeurl@1.0.1
12 silly saveTree │ ├── escape-html@1.0.3
12 silly saveTree │ ├── etag@1.8.1
12 silly saveTree │ ├─┬ finalhandler@1.1.0
12 silly saveTree │ │ └── parseurl@1.3.2
12 silly saveTree │ ├── fresh@0.5.2
12 silly saveTree │ ├── merge-descriptors@1.0.1
12 silly saveTree │ ├── methods@1.1.2
12 silly saveTree │ ├── parseurl@1.3.2
12 silly saveTree │ ├── path-to-regexp@0.1.7
12 silly saveTree │ ├─┬ proxy-addr@2.0.2
12 silly saveTree │ │ ├── forwarded@0.1.2
12 silly saveTree │ │ └── ipaddr.js@1.5.2
12 silly saveTree │ ├── range-parser@1.2.0
12 silly saveTree │ ├─┬ send@0.16.1
12 silly saveTree │ │ ├── destroy@1.0.4
12 silly saveTree │ │ └── mime@1.4.1
12 silly saveTree │ ├── serve-static@1.13.1
12 silly saveTree │ ├── setprototypeof@1.1.0
12 silly saveTree │ ├── utils-merge@1.0.1
12 silly saveTree │ └── vary@1.1.2
12 silly saveTree ├── moment@2.19.1
12 silly saveTree ├── mongoose-find-one-or-create@0.2.0
12 silly saveTree ├── mongoose-find-or-create@1.3.1
12 silly saveTree ├─┬ mongoose@4.13.1
12 silly saveTree │ ├── async@2.1.4
12 silly saveTree │ ├── bson@1.0.4
12 silly saveTree │ ├── hooks-fixed@2.0.2
12 silly saveTree │ ├── kareem@1.5.0
12 silly saveTree │ ├── lodash.get@4.4.2
12 silly saveTree │ ├─┬ mongodb@2.2.33
12 silly saveTree │ │ ├── es6-promise@3.2.1
12 silly saveTree │ │ ├─┬ mongodb-core@2.1.17
12 silly saveTree │ │ │ └─┬ require_optional@1.0.1
12 silly saveTree │ │ │   ├── resolve-from@2.0.0
12 silly saveTree │ │ │   └── semver@5.4.1
12 silly saveTree │ │ └─┬ readable-stream@2.2.7
12 silly saveTree │ │   ├── buffer-shims@1.0.0
12 silly saveTree │ │   ├── core-util-is@1.0.2
12 silly saveTree │ │   ├── isarray@1.0.0
12 silly saveTree │ │   ├── process-nextick-args@1.0.7
12 silly saveTree │ │   ├── string_decoder@1.0.3
12 silly saveTree │ │   └── util-deprecate@1.0.2
12 silly saveTree │ ├── mpath@0.3.0
12 silly saveTree │ ├── mpromise@0.5.5
12 silly saveTree │ ├─┬ mquery@2.3.2
12 silly saveTree │ │ ├── bluebird@3.5.1
12 silly saveTree │ │ ├── regexp-clone@0.0.1
12 silly saveTree │ │ └── sliced@0.0.5
12 silly saveTree │ ├── muri@1.3.0
12 silly saveTree │ ├── regexp-clone@0.0.1
12 silly saveTree │ └── sliced@1.0.1
12 silly saveTree ├─┬ node-fetch@1.7.3
12 silly saveTree │ ├── encoding@0.1.12
12 silly saveTree │ └── is-stream@1.1.0
12 silly saveTree └── raw-body@2.3.2
13 verbose stack SyntaxError: Unexpected end of JSON input
13 verbose stack     at JSON.parse (<anonymous>)
13 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/utils/parse-json.js:3:15)
13 verbose stack     at BB.join (/usr/local/lib/node_modules/npm/lib/install/read-shrinkwrap.js:31:20)
13 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
13 verbose stack     at Holder$3._callFunction (eval at generateHolderClass (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
13 verbose stack     at Holder$3.checkFulfillment (eval at generateHolderClass (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
13 verbose stack     at Promise.eval (eval at thenCallback (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
13 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
13 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
13 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
13 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
13 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:582:21)
13 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
13 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
13 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
13 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
14 verbose cwd /Users/kristerjohansson/Documents/git/test
15 verbose Darwin 17.3.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "mongoose-unique-array" "--save"
17 verbose node v9.3.0
18 verbose npm  v5.6.0
19 error Unexpected end of JSON input
20 verbose exit [ 1, true ]
`

**Comment by vkarpov15** [comment]
Looks like there's an error in your shrinkwrap file, installing the unique array plugin works for me:

```
$ npm install mongoose-unique-array
npm WARN saveError ENOENT: no such file or directory, open '/home/val/Workspace/MongoDB/troubleshoot-mongoose/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/val/Workspace/MongoDB/troubleshoot-mongoose/package.json'
npm WARN mongoose-legacy-pluralize@1.0.1 requires a peer of mongoose@* but none is installed. You must install peer dependencies yourself.
npm WARN mongoose-unique-array@0.2.0 requires a peer of mongoose@>= 4.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN troubleshoot-mongoose No description
npm WARN troubleshoot-mongoose No repository field.
npm WARN troubleshoot-mongoose No README data
npm WARN troubleshoot-mongoose No license field.

+ mongoose-unique-array@0.2.0
added 1 package and removed 1 package in 1.776s
$ 
```
